Realstax/react-rxd

src/Modal/Modal.scss, src/Modal/close-icon.svg, src/Modal/index.js, webpack.config.js
=> Add modal component

package.json, src/Input/index.js, src/Modal/index.js
=> add stateful wrapper to Input

src/Input/index.js, src/Modal/Modal.scss, src/Modal/index.js
add cursor pointer to modal header button
fix modal export
@ThatOtherPerson
=> fix StatefulInput wrapper

src/Table/Table.scss
Evan wanted to change the box shadow.
=> Tweak box shadow

package.json, src/Avatar/Avatar.scss
=> fix avatar image not fitting on IE

circle.yml
=> auto publish on merge to master

package.json, src/Card/Card.scss, src/_common.scss
BWEB-381 #comment fixed in react-rxd, just need to update react-rxd in broker-web
=> Change card style

circle.yml, package.json, src/Card/Card.scss
=> Release 1.1.15

package.json
@ThatOtherPerson need to bump version with every commit to `develop`
=> bump to 1.1.16

circle.yml
=> Release 1.1.16

package.json, src/Modal/index.js
=> add className prop to Modal Body

package.json, src/Modal/index.js
- added className to Modal.Body
=> Release 1.1.17

src/Modal/Modal.scss
=> fixes BWEB-395

src/Modal/Modal.scss
=> Release 1.1.18

package.json, src/Modal/Modal.scss
* fix modal width on mobile
* bump version 1.1.19
* fix modal width
=> Release 1.1.19

package.json, src/Modal/Modal.scss, src/Modal/index.js
=> Release 1.1.21

package.json, src/Grid/index.js, src/Panel/Panel.scss, src/Panel/index.js, src/Table/index.js
=> responsive table.

package.json, src/Badge/Badge.scss
added default background color of $grey to badge component
=> bump to 1.1.25

package.json, src/Avatar/Avatar.scss, src/Badge/Badge.scss, src/Button/Button.scss, src/Card/Card.scss, src/Checkbox/Checkbox.scss, src/Input/Input.scss, src/Modal/Modal.scss, src/Popover/Popover.scss, src/Status/Status.scss, src/Switch/Switch.scss, src/_common.scss
Squashed commits:
[2961476] typography fixes
=> fix css module ident (+1 squashed commit)

package.json, src/Avatar/Avatar.scss
add background color back to avatar
=> Release 1.3.3

package.json, src/Animatable/Bodymovin.js, src/Animatable/index.js, src/Modal/Modal.scss, src/Modal/index.js, yarn.lock
=> Release 1.4.4

package.json, src/Animatable/Bodymovin.js
Add support animation callbacks
=> Release 1.4.6

package.json, src/BoxAlignment/VerticalCenter.js, src/BoxAlignment/VerticalCenter.scss, src/BoxAlignment/index.js, webpack.config.js
Add box alignment - vertical centering component.
=> Release 1.4.7

package.json, src/Checkbox/index.js, src/Input/index.js, src/Modal/index.js
add className props to modals
fixed controlled inputs
=> general bug fixes
